package raytracer.camera;

import java.lang.Math;
import java.awt.Color;

import raytracer.Vector2f;
import raytracer.Vector3f;

/**
 * Class representing the image generated by the camera object.
 * @author Manuel Nunes
 *
 */
public class ImageSensor {
	private int width;
	private int height;
	private Color pixels[][];

	/**
	 * Default constructor.
	 */
	public ImageSensor() {
		this(400, 400);
	}

	/**
	 * Constructor
	 * @param width image width
	 * @param height image height
	 */
	public ImageSensor(int width, int height) {
		this.width = width;
		this.height = height;
		pixels = new Color[width][height];
		for (int x = 0; x < width; ++x) {
			for (int y = 0; y < height; ++y) {
				pixels[x][y] = Color.BLACK;
			}
		}
	}

	/**
	 * Set pixel for position (x,y) in image sensor.
	 * @param x
	 * @param y
	 * @param pixel Radiance
	 */
	public void setPixel(int x, int y, Vector3f pixel) {
		pixels[x][y] = new Color(pixel.get(0), pixel.get(1), pixel.get(2));
	}

	/**
	 * Get pixel for position (x,y) in image sensor.
	 * @param x
	 * @param y
	 * @return Radiance @ (x,y)
	 */
	public Color getPixelColor(int x, int y) {
		return pixels[x][y];
	}

	/**
	 * Getter
	 * @return Image sensor width.
	 */
	public int getWidth() {
		return width;
	}

	/**
	 * Getter
	 * @return Image sensor height.
	 */
	public int getHeight() {
		return height;
	}

	/**
	 * Sample random point within the pixel (x,y)
	 * @param x
	 * @param y
	 * @return sample within [x-0.5,y-0.5]->[x+0.5,y+0.5]
	 */
	public Vector2f samplePixelPoint(int x, int y) {
		float x_sample = (float) x - 0.5f * ((float) width - 1.0f) + (float) Math.random();
		float y_sample = (float) y - 0.5f * ((float) height - 1.0f) + (float) Math.random();
		return new Vector2f(x_sample, y_sample);
	}
}
